/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database.frame;

import database.Conexion;
import database.Alumno;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pnocedalopez
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    DefaultTableModel tabla = new DefaultTableModel();
    public MainFrame() {
        initComponents();
        jB_GuardarCambios.setVisible(false);
        tabla.addColumn("ID");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDOS");
        tabla.addColumn("FECHA NACIMIENTO");
        tabla.addColumn("NOTA");
        jTableAlumnos.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jBVer = new javax.swing.JButton();
        jBAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jLabelID = new javax.swing.JLabel();
        javax.swing.JLabel jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLIDO = new javax.swing.JLabel();
        jLabelFECHA = new javax.swing.JLabel();
        jLabelNOTA = new javax.swing.JLabel();
        jTF_ID = new javax.swing.JTextField();
        jTF_NOMBRE = new javax.swing.JTextField();
        jTF_APELLIDOS = new javax.swing.JTextField();
        jTF_FECHA = new javax.swing.JTextField();
        jTF_NOTA = new javax.swing.JTextField();
        jB_Borrar = new javax.swing.JButton();
        jB_Buscar = new javax.swing.JButton();
        jTF_Busqueda = new javax.swing.JTextField();
        jB_Modificar = new javax.swing.JButton();
        jB_GuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de Datos");

        jBVer.setText("Ver Datos");
        jBVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerActionPerformed(evt);
            }
        });

        jBAñadir.setText("Nuevo Alumno");
        jBAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAñadirActionPerformed(evt);
            }
        });

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDOS", "FECHA NACIMIENTO", "NOTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);

        jLabelID.setText("ID:");

        jLabelNOMBRE.setText("NOMBRE:");

        jLabelAPELLIDO.setText("APELLIDOS:");

        jLabelFECHA.setText("FECHA DE NACIMIENTO:");

        jLabelNOTA.setText("NOTA");

        jB_Borrar.setText("Borrar Alumno");
        jB_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BorrarActionPerformed(evt);
            }
        });

        jB_Buscar.setText("Buscar");
        jB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BuscarActionPerformed(evt);
            }
        });

        jB_Modificar.setText("Modificar Alumno");
        jB_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ModificarActionPerformed(evt);
            }
        });

        jB_GuardarCambios.setText("Guardar Cambios");
        jB_GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID)
                            .addComponent(jLabelFECHA)
                            .addComponent(jLabelNOMBRE)
                            .addComponent(jLabelAPELLIDO)
                            .addComponent(jLabelNOTA))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jB_Modificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBVer, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_Borrar)
                                    .addComponent(jBAñadir)))
                            .addComponent(jB_GuardarCambios)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jB_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNOMBRE)
                            .addComponent(jTF_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAPELLIDO))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFECHA)
                            .addComponent(jTF_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNOTA)
                            .addComponent(jTF_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jBVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Modificar)
                        .addGap(30, 30, 30)
                        .addComponent(jB_GuardarCambios)
                        .addGap(22, 22, 22)
                        .addComponent(jBAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_Borrar)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerActionPerformed
        for (int i=0; i<tabla.getRowCount();i++){
            tabla.removeRow(i);
            i-=1;
        }
        ArrayList alumnos = Conexion.mostrarAlumnos();
        Iterator it = alumnos.iterator();
        while(it.hasNext()){
            Alumno alu = (Alumno) it.next();
            String[] fila = new String[5];
            fila[0] = String.valueOf(alu.getId());
            fila[1] = alu.getNombre();
            fila[2] = alu.getApellidos();
            fila[3] = String.valueOf(alu.getFechaNaciemiento());
            fila[4] = String.valueOf(alu.getNota());
            tabla.addRow(fila);
            jTableAlumnos.setModel(tabla);
        }
    }//GEN-LAST:event_jBVerActionPerformed

    private void jBAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAñadirActionPerformed
        Alumno alu = new Alumno(Integer.parseInt(jTF_ID.getText()),jTF_NOMBRE.getText(),jTF_APELLIDOS.getText(),
                jTF_FECHA.getText(),Integer.parseInt(jTF_NOTA.getText()));
        Conexion.añadirAlumno(alu);
    }//GEN-LAST:event_jBAñadirActionPerformed

    private void jB_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BorrarActionPerformed
        try{
            int id = Integer.parseInt(String.valueOf(jTableAlumnos.getValueAt(jTableAlumnos.getSelectedRow(), jTableAlumnos.getSelectedColumn())));
            Conexion.borrarAlumno(id);
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(rootPane, "No has selecionado un alumno");
        }   
    }//GEN-LAST:event_jB_BorrarActionPerformed

    private void jB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BuscarActionPerformed
        for (int i=0; i<tabla.getRowCount();i++){
            tabla.removeRow(i);
            i-=1;
        }
        if (jTF_Busqueda.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "No se ha introducido ninguna busqueda");
        }else{
            ArrayList alumnos = Conexion.busqueda(jTF_Busqueda.getText());
            if (alumnos.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "No se han encontrado coincidencias");
            }
            else{
                Iterator it = alumnos.iterator();
                while(it.hasNext()){
                    Alumno alu = (Alumno) it.next();
                    String[] fila = new String[5];
                    fila[0] = String.valueOf(alu.getId());
                    fila[1] = alu.getNombre();
                    fila[2] = alu.getApellidos();
                    fila[3] = String.valueOf(alu.getFechaNaciemiento());
                    fila[4] = String.valueOf(alu.getNota());
                    tabla.addRow(fila);
                    jTableAlumnos.setModel(tabla);
                }
            }
        }
    }//GEN-LAST:event_jB_BuscarActionPerformed

    private void jB_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ModificarActionPerformed
        try{
            jB_GuardarCambios.setVisible(true);
            int id = Integer.parseInt(String.valueOf(jTableAlumnos.getValueAt(jTableAlumnos.getSelectedRow(), jTableAlumnos.getSelectedColumn())));
            Alumno alu = Conexion.buscarAlumno(id);
            jTF_ID.setText(String.valueOf(alu.getId()));
            jTF_ID.setEditable(false);
            jTF_NOMBRE.setText(alu.getNombre());
            jTF_APELLIDOS.setText(alu.getApellidos());
            jTF_FECHA.setText(alu.getFechaNaciemiento());
            jTF_NOTA.setText(String.valueOf(alu.getNota()));
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(rootPane, "No has selecionado un alumno");
        }   
    }//GEN-LAST:event_jB_ModificarActionPerformed

    private void jB_GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GuardarCambiosActionPerformed
        Alumno nuevo = new Alumno(Integer.parseInt(jTF_ID.getText()),jTF_NOMBRE.getText(),jTF_APELLIDOS.getText(),
            jTF_FECHA.getText(), Integer.parseInt(jTF_NOTA.getText()));
        Conexion.modificarAlumno(nuevo);
    }//GEN-LAST:event_jB_GuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAñadir;
    private javax.swing.JButton jBVer;
    private javax.swing.JButton jB_Borrar;
    private javax.swing.JButton jB_Buscar;
    private javax.swing.JButton jB_GuardarCambios;
    private javax.swing.JButton jB_Modificar;
    private javax.swing.JLabel jLabelAPELLIDO;
    private javax.swing.JLabel jLabelFECHA;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNOTA;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_APELLIDOS;
    private javax.swing.JTextField jTF_Busqueda;
    private javax.swing.JTextField jTF_FECHA;
    private javax.swing.JTextField jTF_ID;
    private javax.swing.JTextField jTF_NOMBRE;
    private javax.swing.JTextField jTF_NOTA;
    private javax.swing.JTable jTableAlumnos;
    // End of variables declaration//GEN-END:variables
}
